server:
  port: 8082

spring:
  application:
    name: "PAYMENT-SERVICE"
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/payment_db
    username: testuser
    password: testuser
    schema: sch_payment
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: sch_payment
  config:
    import: configserver:http://localhost:9296

management:
  tracing:
    sampling:
      probability: 1.0
