server:
  port: 8081

spring:
  application:
    name: "ORDER-SERVICE"
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/order_db
    username: testuser
    password: testuser
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: sch_order
  config:
    import: configserver:http://localhost:9296




management:
  tracing:
    sampling:
      probability: 1.0
      
resilience4j:
  circuitbreaker:
    instances:
      external:
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
      
      
      
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8701/eureka}